#Rename this to extra_model_paths.yaml and ComfyUI will load it

main:
  base_path: /root/autodl-tmp/models
  checkpoints: checkpoint
  configs: checkpoint
  vae: vae
  loras: loras
  upscale_models: upscale_models
  embeddings: embeddings
  hypernetworks: embeddings
  controlnet: controlnet
  ipadapter: ip_adapter
  clip: clip
  clip_vision: clip_vision
  unet: unet
  animatediff_models: animatediff_models
  animatediff_motion_lora: animatediff_lora
  # wd14_tagger: wd14_tagger
  birefnet: BiRefNet
  sams: sams
  grounding-dino: grounding-dino
  diffusion_models: diffusion_models
  text_encoders: text_encoders

sys:
  base_path: /root/models
  checkpoints: checkpoint
  configs: checkpoint
  vae: vae
  loras: loras
  upscale_models: upscale_models
  embeddings: embeddings
  hypernetworks: embeddings
  controlnet: controlnet
  ipadapter: ip_adapter
  clip: clip
  clip_vision: clip_vision
  unet: unet
  animatediff_models: animatediff_models
  animatediff_motion_lora: animatediff_lora
  wd14_tagger: wd14_tagger
  birefnet: BiRefNet
  sams: sams
  grounding-dino: grounding-dino
  diffusion_models: diffusion_models
  text_encoders: text_encoders

fs:
  base_path: /root/autodl-fs/models
  checkpoints: checkpoint
  configs: checkpoint
  vae: vae
  loras: loras
  upscale_models: upscale_models
  embeddings: embeddings
  hypernetworks: embeddings
  controlnet: controlnet
  ipadapter: ip_adapter
  clip: clip
  clip_vision: clip_vision
  unet: unet
  animatediff_models: animatediff_models
  animatediff_motion_lora: animatediff_lora
  # wd14_tagger: wd14_tagger
  birefnet: BiRefNet
  sams: sams
  grounding-dino: grounding-dino
  diffusion_models: diffusion_models
  text_encoders: text_encoders
