configs:
  name: sd15
  tmp_path: /root/autodl-tmp
  skip_mark_path: /root/autodl-tmp/.skip_init_files_sd15

files:
  # checkpoints
  - type: codewithgpu
    cg_path: StableDiffusion-checkpoints/majicmixRealistic_v7.safetensors
    target: /root/autodl-tmp/ComfyUI/models/checkpoints/

  # vae
  - type: codewithgpu
    cg_path: StableDiffusion-VAE/vae-ft-mse-840000-ema-pruned.safetensors
    target: /root/autodl-tmp/ComfyUI/models/vae/

  # loras
  - type: codewithgpu
    cg_path: StableDiffusion-LoRAs/sd15_lcm_lora_rank1.safetensors
    target: /root/autodl-tmp/ComfyUI/models/loras/

  # embeddings
  - type: codewithgpu
    cg_path: StableDiffusion-Embeddings/easy_negative.safetensors
    target: /root/autodl-tmp/ComfyUI/models/embeddings/
