configs:
  name: llm
  tmp_path: /root/autodl-tmp
  skip_mark_path: /root/autodl-tmp/skip_init_files_llm

files:
  # ollama
  - type: codewithgpu
    cg_path: ollama/sha256-43f7a214e5329f672bb05404cfba1913cbb70fdaa1a17497224e1925046b0ed5
    target: /root/models/ollama/
