configs:
  name: nunchaku_qwen_image
  tmp_path: /root/autodl-tmp
  skip_mark_path: /root/autodl-tmp/skip_init_files_nunchaku_qwen_image

files:
  - type: codewithgpu
    cg_path: tzwm_qwen-image/svdq-int4_r128-qwen-image-lightningv1.1-8steps.safetensors
    autodl_path: /.autodl/0f/75/6c/0f756cdd285dd8443ff3773dbe2020da
    target: /root/autodl-tmp/models/diffusion_models/
    blackwell:
      cg_path: tzwm_qwen-image/svdq-fp4_r128-qwen-image-lightningv1.1-8steps.safetensors
      autodl_path: /.autodl/72/e0/a2/72e0a2cdc29e8795156f4decbaf0e1b5

  - type: codewithgpu
    cg_path: tzwm_qwen-image/svdq-int4_r128-qwen-image-edit-2509-lightningv2.0-4steps.safetensors
    autodl_path: /.autodl/4b/a9/4c/4ba94c933a9a9fd299930c62702ffbb2
    target: /root/autodl-tmp/models/diffusion_models/
    blackwell:
      cg_path: tzwm_qwen-image/svdq-fp4_r128-qwen-image-edit-2509-lightningv2.0-4steps.safetensors
      autodl_path: /.autodl/c7/fd/d9/c7fdd9e3d60622aa87a3f3aace274c50

  # vae
  - type: codewithgpu
    cg_path: tzwm_qwen-image/qwen_image_vae.safetensors
    autodl_path: /.autodl/5f/09/a1/5f09a128b4c05c9998b9f218dc137b7b
    target: /root/autodl-tmp/models/vae/

  # clip
  - type: codewithgpu
    cg_path: tzwm_qwen-image/qwen_2.5_vl_7b_fp8_scaled.safetensors
    autodl_path: /.autodl/b8/98/22/b89822a44279e6d83c06a5061d7b1ca6
    target: /root/autodl-tmp/models/clip/
